# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: FamilyFileAppCICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4  #دریافت کد از Repository

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4  # اکشن رسمی برای نصب دات‌نت
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore FamilyFile.sln

    - name: Build project
      run: dotnet build FamilyFile.sln --configuration Release --no-restore  #کامپایل کردن پروژه در حالت پروداکشن
      # --no-restore چون قبلاً restore انجام شده
      #-configuration Release کامپیایل کردن پروژه در حالت پروداکشن
      ##dotnet build --configuration Release --output ./artifacts  برای تغییر مسیر خروجی

      
    - name: Run unit tests  
      run: dotnet test FamilyFile.sln --no-restore --verbosity normal
     # --verbosity normal برای لاگ‌های شفاف در کنسول
     ##یعنی خروجی‌ها خوانا و شامل نتایج تست‌ها خواهند بود

    #کاربرد: سطح جزئیات خروجی (لاگ) دستور را تعیین می‌کند.
    #quiet: حداقل خروجی (فقط خطاها).
    #minimal: خروجی مختصر (مانند تعداد تست‌های موفق/ناموفق).
    #normal: خروجی استاندارد (شامل نام تست‌ها، نتایج، و خلاصه نهایی).
    #detailed: جزئیات بیشتری از فرآیند بیلد و تست.
    #diagnostic: جزئیات کامل (برای عیب‌یابی پیشرفته).


